---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.39.0
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: test
    image: golang:1.16
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: registry.megpoid.xyz/drone-kaniko
    settings:
      repo: registry.megpoid.xyz/swarm-updater
      tags: latest
      registry: registry.megpoid.xyz
      mirror: http://registry:5000
      build_args_from_env:
        - GOPROXY
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
        - CI_COMMIT_BRANCH=${DRONE_BRANCH}
        - CI_COMMIT_SHA=${DRONE_COMMIT_SHA}
        - CI_PIPELINE_CREATED_AT=${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_appkey
      template: |
        {
          "images": [
            "registry.megpoid.xyz/swarm-updater"
          ]
        }
trigger:
  branch:
    - master
