#!/bin/bash

set -eux

if [ "$DOCKER_TAG" == "latest" ]
then
  export COMMIT_TAG=
else
  export COMMIT_TAG="${DOCKER_TAG}"
fi

docker build \
  --build-arg CI_COMMIT_TAG="${COMMIT_TAG}" \
  --build-arg CI_COMMIT_BRANCH="${SOURCE_BRANCH}" \
  --build-arg CI_COMMIT_SHA="${SOURCE_COMMIT}" \
  --build-arg CI_PIPELINE_CREATED_AT="$(date -u +"%s")" \
  -t "${IMAGE_NAME}" .
